# Nearest neighbor for spine injury classification

In this homework notebook we use **nearest neighbor classification** to classify back injuries for patients in a hospital, based on measurements of the shape and orientation of their pelvis and spine.

The data set contains information from **310** patients. For each patient, there are: six measurements (the x) and a label (the y). The label has **3** possible values, `’NO’` (normal), `’DH’` (herniated disk), or `’SL’` (spondilolysthesis).

**Note:** Before attempting this homework, please go through the <font color="magenta">*Nearest neighbor for handwritten digit recognition*</font> notebook.

# 1. Setup notebook

We import all necessary packages for the homework. Notice that we do **NOT** import any of the `sklearn` packages. This is because we want you to implement a nearest neighbor classifier **manually**, as in the <font color="magenta">*Nearest neighbor for handwritten digit recognition*</font> notebook.


In [1]:
import numpy as np

We now load the dataset. We divide the data into a training set of 248 patients and a separate test set of 62 patients. The following arrays are created:

* **`trainx`** : The training data's features, one point per row.
* **`trainy`** : The training data's labels.
* **`testx`** : The test data's features, one point per row.
* **`testy`** : The test data's labels.

We will use the training set (`trainx` and `trainy`), with nearest neighbor classification, to predict labels for the test data (`testx`). We will then compare these predictions with the correct labels, `testy`.

Notice that we code the three labels as `0. = ’NO’, 1. = ’DH’, 2. = ’SL’`.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
!ls "/content/drive/MyDrive/Colab Notebooks/UCSanDiegoX DSE220x Machine Learning Fundamentals/NN_spine/"
localFolder = "/content/drive/MyDrive/Colab Notebooks/UCSanDiegoX DSE220x Machine Learning Fundamentals/NN_spine/"

column_3C.dat  confusion_matrix.png  Nearest_neighbor_spine.ipynb
/content/drive/MyDrive/Colab Notebooks/UCSanDiegoX DSE220x Machine Learning Fundamentals/NN_spine/column_3C.dat


In [19]:
# Load data set and code labels as 0 = ’NO’, 1 = ’DH’, 2 = ’SL’
labels = ['NO', 'DH', 'SL']
data = np.loadtxt(f'{localFolder}column_3C.dat', converters={6: lambda s: labels.index(s)} )

# Separate features from labels
x = data[:,0:6]
y = data[:,6]

# Divide into training and test set
training_indices = list(range(0,20)) + list(range(40,188)) + list(range(230,310))
test_indices = list(range(20,40)) + list(range(188,230))

trainx = x[training_indices,:]
trainy = y[training_indices]
testx = x[test_indices,:]
testy = y[test_indices]

## 2. Nearest neighbor classification with L2 distance

In this exercise we will build a nearest neighbor classifier based on L2 (*Euclidean*) distance.

<font color="magenta">**For you to do:**</font> Write a function, **NN_L2**, which takes as input the training data (`trainx` and `trainy`) and the test points (`testx`) and predicts labels for these test points using 1-NN classification. These labels should be returned in a `numpy` array with one entry per test point. For **NN_L2**, the L2 norm should be used as the distance metric.


<font  style="color:blue"> **Code**</font>
```python
# test function
testy_L2 = NN_L2(trainx, trainy, testx)
print( type( testy_L2) )
print( len(testy_L2) )
print( testy_L2[40:50] )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
62
[ 2.  2.  1.  0.  0.  0.  0.  0.  0.  0.]
```


In [40]:
# Modify this Cell
def squared_distance(x,y):
  return np.sum(np.square(x-y))

def findNN_L2(x,train_values,train_labels):
  distances = [squared_distance(x, train_values[i]) for i in range(len(train_labels))]
  return np.argmin(distances)

def NN_L2(trainx, trainy, testx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy

    ### BEGIN SOLUTION
    final_prediction = [trainy[findNN_L2(testx[x,],trainx,trainy)] for x in range(len(testx))]
    return np.array(final_prediction)
    ### END SOLUTION

testy_L2 = NN_L2(trainx, trainy, testx)
print( type( testy_L2) )
print( len(testy_L2) )
print( testy_L2[40:50] )

<class 'numpy.ndarray'>
62
[2. 2. 1. 0. 0. 0. 0. 0. 0. 0.]


After you are done, run the cell below to check your function. If an error is triggered, you should go back and revise your function.

In [39]:
testy_L2 = NN_L2(trainx, trainy, testx)

assert( type( testy_L2).__name__ == 'ndarray' )
assert( len(testy_L2) == 62 )
assert( np.all( testy_L2[50:60] == [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  0.,  0.] )  )
assert( np.all( testy_L2[0:10] == [ 0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.] ) )

# 3. Nearest neighbor classification with L1 distance

We now compute nearest neighbors using the L1 distance (sometimes called *Manhattan Distance*).

<font color="magenta">**For you to do:**</font> Write a function, **NN_L1**, which again takes as input the arrays `trainx`, `trainy`, and `testx`, and predicts labels for the test points using 1-nearest neighbor classification. For **NN_L1**, the L1 distance metric should be used. As before, the predicted labels should be returned in a `numpy` array with one entry per test point.

Notice that **NN_L1** and **NN_L2** may well produce different predictions on the test set.


<font  style="color:blue"> **Code**</font>
```python
# test function
testy_L2 = NN_L2(trainx, trainy, testx)
testy_L1 = NN_L1(trainx, trainy, testx)

print( type( testy_L1) )
print( len(testy_L1) )
print( testy_L1[40:50] )
print( all(testy_L1 == testy_L2) )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
62
[ 2.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
False
```


In [48]:
# Modify this Cell
def manhattan_distance(x,y):
  return np.sum(abs(x-y))

def findNN_L1(x,train_values,train_labels):
  distances = [manhattan_distance(x, train_values[i]) for i in range(len(train_labels))]
  return np.argmin(distances)

def NN_L1(trainx, trainy, testx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy

    ### BEGIN SOLUTION
    final_prediction = [trainy[findNN_L1(testx[x,],trainx,trainy)] for x in range(len(testx))]
    return np.array(final_prediction)
    ### END SOLUTION

# test function
testy_L2 = NN_L2(trainx, trainy, testx)
testy_L1 = NN_L1(trainx, trainy, testx)

print( type( testy_L1) )
print( len(testy_L1) )
print( testy_L1[40:50] )
print( all(testy_L1 == testy_L2) )

<class 'numpy.ndarray'>
62
[2. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
False


Again, use the following cell to check your code.

In [51]:
testy_L1 = NN_L1(trainx, trainy, testx)
testy_L2 = NN_L2(trainx, trainy, testx)

assert( type( testy_L1).__name__ == 'ndarray' )
assert( len(testy_L1) == 62 )
assert( not all(testy_L1 == testy_L2) )
assert( all(testy_L1[50:60]== [ 0.,  2.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.]) )
assert( all( testy_L1[0:10] == [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.]) )

# 4. Test errors and the confusion matrix

Let's see if the L1 and L2 distance functions yield different error rates for nearest neighbor classification of the test data.

In [52]:
def error_rate(testy, testy_fit):
    return float(sum(testy!=testy_fit))/len(testy)

print("Error rate of NN_L1: ", error_rate(testy,testy_L1) )
print("Error rate of NN_L2: ", error_rate(testy,testy_L2) )

Error rate of NN_L1:  0.22580645161290322
Error rate of NN_L2:  0.20967741935483872


We will now look a bit more deeply into the specific types of errors made by nearest neighbor classification, by constructing the <font color="magenta">*confusion matrix*</font>.

Since there are three labels, the confusion matrix is a 3x3 matrix whose rows correspond to the true label and whose columns correspond to the predicted label. For example, the entry at row DH, column SL, contains the number of test points whose correct label was DH but which were classified as SL.

<img style="width:200px" src="confusion_matrix.png">




Write a function, **confusion**, which takes as input the true labels for the test set (that is, `testy`) as well as the predicted labels and returns the confusion matrix. The confusion matrix should be a `np.array` of shape `(3,3)` .

<font  style="color:blue"> **Code**</font>
```python
L2_neo = confusion(testy, testy_L2)  
print( type(L2_neo) )
print( L2_neo.shape )
print( L2_neo )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
(3, 3)
[[ 17.   1.   2.]
 [ 10.  10.   0.]
 [  0.   0.  22.]]
```


In [72]:
# Modify this cell

def confusion(testy,testy_fit):
    # inputs: the correct labels, the fitted NN labels
    # output: a 3x3 np.array representing the confusion matrix as above

    ### BEGIN SOLUTION

    confusion_matrix = np.zeros((3, 3))
    for i in range(len(testy_fit)):
        confusion_matrix[int(testy[i])][int(testy_fit[i])] += 1
    return confusion_matrix
    ### END SOLUTION

L2_neo = confusion(testy, testy_L2)
print( type(L2_neo) )
print( L2_neo.shape )
print( L2_neo )

<class 'numpy.ndarray'>
(3, 3)
[[17.  1.  2.]
 [10. 10.  0.]
 [ 0.  0. 22.]]


In [91]:
# Modify this cell

def confusion_any_test(testy,testy_fit):
    # confusion matrix for any labels and size matrix, you can use for testes like ''

    ### BEGIN SOLUTION
    label_to_index = {label: idx for idx, label in enumerate(testy)}

    indexes = np.array(sorted(list(label_to_index.keys())))
    print(indexes)
    confusion_matrix = np.zeros((indexes.size, indexes.size))

    for i in range(len(testy)):
      row_idx = np.where(indexes == testy[i])[0][0]
      col_idx = np.where(indexes == testy_fit[i])[0][0]
      confusion_matrix[row_idx][col_idx] += 1

    return confusion_matrix
    ### END SOLUTION

L2_neo_any = confusion_any_test(testy, testy_L2)
print( type(L2_neo_any) )
print( L2_neo_any.shape )
print( L2_neo_any )

[0. 1. 2.]
<class 'numpy.ndarray'>
(3, 3)
[[17.  1.  2.]
 [10. 10.  0.]
 [ 0.  0. 22.]]


Now check your code by running the following cell.

In [93]:
# Test Function

L1_neo = confusion(testy, testy_L1)
assert( type(L1_neo).__name__ == 'ndarray' )
assert( L1_neo.shape == (3,3) )
assert( np.all(L1_neo == [[ 16.,  2.,  2.],[ 10.,  10.,  0.],[ 0.,  0.,  22.]]) )
L2_neo = confusion(testy, testy_L2)
assert( np.all(L2_neo == [[ 17.,  1.,  2.],[ 10.,  10.,  0.],[ 0.,  0.,  22.]]) )

# 5. Some questions for you

*Note down the answers to these, since you will need to enter them as part of this week's assignment.*

* In the test set, which class (NO, DH, or SL) was **most frequently** misclassified by the L1-based nearest neighbor classifier?
* In the test set, which class (NO, DH, or SL) was **never** misclassified by the L2-based nearest neighbor classifier?
* On **how many** of the test points did the two classification schemes (based on L1 and L2 distance) yield *different* predictions?


In [131]:
print("The class was most frequently misclassified by the L1-based: ")
misclassified_arr = [[L1_neo[x][y] if(x != y) else 0 for y in range(len(L1_neo[x]))]  for x in range(len(L1_neo))]
misclassified_arr = [np.sum(misclassified_arr[x]) for x in range(len(misclassified_arr))]
print(np.argmax(misclassified_arr)," or ",labels[np.argmax(misclassified_arr)])


print("\nThe class was never misclassified by the L2-based: ")
misclassified_arr = [[0 if(x == y or L1_neo[x][y] == 0) else 1 for y in range(len(L2_neo[x]))]  for x in range(len(L2_neo))]
misclassified_arr = [x for x in range(len(misclassified_arr)) if np.sum(misclassified_arr[x]) == 0]
print(misclassified_arr[0]," or ",labels[misclassified_arr[0]])

print("\nHow many of the test points did the two classification schemes: ")
total_diff = np.sum(testy_L1 != testy_L2)
print(int(total_diff))

The class was most frequently misclassified by the L1-based: 
1  or  DH

The class was never misclassified by the L2-based: 
2  or  SL

How many of the test points did the two classification schemes: 
7
